#关联表 其中除主键外 外键关系和非空校验都在服务层中实现
CREATE TABLE `TB_ROLE_USER` (
  `ROLE_ROW_ID` bigint(20) DEFAULT NULL,
  `USER_ROW_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
#角色表
CREATE TABLE `TB_ROLE` (
  `ROW_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE_TYPE` int(11) DEFAULT NULL,
  `ROLE_NAME` varchar(30) DEFAULT NULL,
  `ROLE_INFO` text,
  `ACTIVE_FLAG` int(11) DEFAULT NULL,
  `CREATE_BY` varchar(30) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(30) DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
#用户表
CREATE TABLE `TB_USER` (
  `ROW_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(30) DEFAULT NULL,
  `USER_ID` varchar(30) DEFAULT NULL,
  `USER_PHOTO` varchar(30) DEFAULT NULL,
  `USER_LOGIN_COUNT` int(11) DEFAULT NULL,
  `USER_LAST_LOGIN_TIME` datetime DEFAULT NULL,
  `USER_LAST_LOGIN_IP` varchar(30) DEFAULT NULL,
  `USER_LOCK` int(11) DEFAULT NULL,
  `ACTIVE_FLAG` int(11) DEFAULT NULL,
  `CREATE_BY` varchar(30) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_BY` varchar(30) DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

